honeycombio/example-greeting-service

ruby/message-service/message.ru

Copy pasta slop. This is the message service, not the year service. 🤦🏻

correct the manual span in Ruby message service

---

node/.gitignore
node/frontend/.dockerignore
node/frontend/.prettierrc.js
node/frontend/Dockerfile
node/frontend/main.js
node/frontend/package-lock.json
node/frontend/package.json

Add NodeJS frontend service.
Currently uses placeholders for name and message URLs.
Includes context for name, user_message, user_name.
To run, add API Key and Dataset and then `npm start` or `npm run dev`

Add NodeJS frontend service

---

Tiltfile
node/README.md
node/docker-compose.yml
node/frontend/main.js
node/message-service/main.js
node/year-service/.dockerignore
node/year-service/.prettierrc.js
node/year-service/Dockerfile
node/year-service/main.js
node/year-service/package-lock.json
node/year-service/package.json
node/year-service/tracing.js

Add NodeJS Year Service with OTLP
Adds support for environment variables
Side note: `//prettier-ignore`s added to keep imports from wrapping to multi-line with printWidth of 80.
Closes #44

Add NodeJS Year Service with OTLP

---

dotnet/Tiltfile
dotnet/docker-compose.yml
dotnet/frontend/Controllers/GreetingController.cs
dotnet/frontend/Dockerfile
dotnet/frontend/frontend.csproj
dotnet/message-service/Controllers/MessageController.cs
dotnet/message-service/Dockerfile
dotnet/message-service/Startup.cs
dotnet/message-service/message-service.csproj
dotnet/name-service/Controllers/NameController.cs
dotnet/name-service/Dockerfile
dotnet/name-service/Startup.cs
dotnet/year-service/Dockerfile
dotnet/year-service/Startup.cs

With this PR, you can change directory to `dotnet/`, run `tilt up` and have a wholly .NET experience that hangs together. Updating the root Tilt could happen in this PR or in a subsequent one, but until that Tilt is taught the same "load messages into Redis" the Message service will always return "generic hello".
Updates the message-dotnet microservice to retrieve a message from Redis to demonstrate redis autoinstrumentation.
Updates the stock OTel services (name and year) to include resource attributes set via environment variable.

more redis usage; run dotnet apps together via tilt and docker

---

Tiltfile
java/frontend/Dockerfile
java/frontend/build.gradle
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/FrontendApplication.java
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/GreetingController.java
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/MessageService.java
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/NameService.java
java/message-service/build.gradle
java/message-service/src/main/java/io/honeycomb/examples/message/MessageService.java
java/name-service/build.gradle
java/name-service/src/main/java/io/honeycomb/examples/name/MessageService.java
java/name-service/src/main/java/io/honeycomb/examples/name/NameController.java
java/name-service/src/main/java/io/honeycomb/examples/name/NameService.java
java/name-service/src/main/java/io/honeycomb/examples/name/YearService.java
java/year-service/build.gradle
java/year-service/gradlew

honeycomb sdk provides the otel api (that matches the underlying sdk version), use the honey sdk instead of explicitly depending on otel api (this is what public docs already recommend)

Update Java to use honey sdk for otel api

---

dotnet/name-service/Controllers/NameController.cs
dotnet/name-service/Startup.cs
dotnet/year-service/Program.cs

Switching the remaining services to use Trace API instead of Activity for consistency.

dotnet: use trace api everywhere

---

golang/docker-compose.yml

- go services run fine in Tilt; this allows it to run without Tilt using docker
- add docker-compose file
- endpoints include `http://`. alternative may be to remove the `http://` in tilt env and docker-compose, and add into the services themselves.

add docker compose for golang

---

.gitignore
ruby/docker-compose.yml
ruby/frontend/Gemfile
ruby/message-service/Dockerfile
ruby/name-service/Dockerfile
ruby/year-service/Dockerfile

- this makes for a quick ruby spinup in docker with docker-compose, and also makes it easier to point to a specific branch for testing when using docker
- ignore `direnv` and `env`-like files
- add `bundle exec` to Dockerfiles
- use latest otel sdk

[ruby] Add docker-compose and adjust dockerfiles

---

java/frontend/Dockerfile
java/frontend/build.gradle
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/MessageService.java
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/NameService.java
java/message-service/Dockerfile
java/message-service/build.gradle
java/name-service/Dockerfile
java/name-service/build.gradle
java/name-service/src/main/java/io/honeycomb/examples/name/YearService.java
java/year-service/Dockerfile
java/year-service/src/main/java/io/honeycomb/examples/javaotlp/YearApplication.java
java/year-service/src/main/java/io/honeycomb/examples/javaotlp/YearService.java

- bring java services up to date with current honeycomb distro
- update to later versions of otel and distro
- remove `-all` suffix
- replace `HoneycombSdk` with `OpenTelemetryConfiguration` builder
Also, oof, not sure why all the whitespace changes. Might need to ignore it for initial review, and I can check it against editorconfig.

update java to newer versions of otel and honey

---

java/message-service/build.gradle
java/name-service/build.gradle
java/year-service/build.gradle

- java services didn't work right because of older version of distro
- update version from 0.4.0 to 0.9.0 (somehow missed in #87)
- swap out "beestro" for "distro"

[java] update distro terminology and version

---

golang/frontend/main.go
golang/message-service/main.go
golang/name-service/main.go
golang/year-service/main.go

This ensures the default SDK attributes are preserved, eg `telemetry.sdk.name` and `telemetry.sdk.version`.
- Merge the default resource with a custom resource that adds the service name in each otel service
- Ensure each service logs it's url it's listening on

Merge default resource with custom attrs

---

.gitignore
.tool-versions
README.md
Tiltfile
node/.gitignore

Currently when running EGS, if you want to run an app that isn't the default language, you have to go into the Tiltfile and manually edit it to run the app in the language ecosystem you'd like. There is [Tilt support for running specific services / groups of services](https://docs.tilt.dev/tiltfile_config.html#run-a-defined-set-of-services) so it's possible to parameterize this without changing very much 🎉 . 
- Updated the Tiltfile to run all services instead of commenting out some of them. This looks 👻 scary 👻  but it's just there so that all the resources can be registered to Tilt, we won't be running all of them.
- Added a group of services that should always run (`collector`, `redis`, `curl greeting`)
- Added groups of services that are common to run together (`go`, `py`, `rb`, …

Parameterize which language or services run with Tilt

---

ruby/frontend/frontend.ru
ruby/frontend/o11y_wrapper.rb

- Lacking example of a Baggage span processor in Ruby
- adds a BaggageSpanProcessor to an example "organization's observability library"
- adds a prototype of "CarryOn" which behaves similarly to Baggage but does not get handed off to other services via propagation

[ruby] add an example of Baggage (& CarryOn) span processors

---

README.md
node/frontend/Dockerfile
node/frontend/main.js
node/frontend/package-lock.json
node/frontend/package.json
node/frontend/tracing.js
node/message-service/main.js
node/name-service/main.js
node/year-service/Dockerfile

- closes #140 
- learned a lot about Node OTel ✨ 
- remove beeline from frontend service
- add node auto instrumentation to frontend service, created tracing.js 
- add a beeline trace context in the name service (and message service) instead of as part of a promise in frontend service
- use `npm start` script to include tracing.js and main.js in docker (match tilt)

Convert node frontend service to OTel 

---

java/frontend/Dockerfile
java/frontend/build.gradle
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/MessageService.java
java/frontend/src/main/java/io/honeycomb/examples/frontend_java/NameService.java
java/message-service/Dockerfile
java/message-service/build.gradle
java/message-service/src/main/java/io/honeycomb/examples/message/MessageService.java
java/name-service/Dockerfile
java/name-service/build.gradle
java/name-service/src/main/java/io/honeycomb/examples/name/MessageService.java
java/name-service/src/main/java/io/honeycomb/examples/name/NameController.java
java/name-service/src/main/java/io/honeycomb/examples/name/NameService.java
java/name-service/src/main/java/io/honeycomb/examples/name/YearService.java
java/year-service/Dockerfile
java/year-service/build.gradle
java/year-service/src/main/java/io/honeycomb/examples/javaotlp/YearService.java

- out-of-date java services
- update to latest otel versions (0.21.0) and honeycomb distro version (1.4.0)
- update deps and imports for `@WithSpan` (`opentelemetry-extension-annotations` moved to `opentelemetry-instrumentation-annotations`)
- remove some unused stuff

maint: update java versions

---

.gitignore

When running `tilt up go` the compiled binaries show up in git status and are just noise; we shouldn't add them. This change tells git to ignore the compiled go binaries.

maint: adding compiled go binaries to gitignore

---

golang/name-service/main.go

Seeding a random number generator is supposed to happen once per program invocation rather than multiple times within the execution of the program. This change moves the rand seed from within the handler to the overall initialization during `main`.

fix: use a single random number seed for the whole program

---

golang/docker-compose.yml
golang/frontend/Dockerfile
golang/message-service/Dockerfile
golang/name-service/Dockerfile
golang/year-service/Dockerfile

- updates #95 
- make it work again since switching to shared go.mod file
- use non-alpine build container because we need git to resolve one of the deps
- copy certs into bin container so we can talk to honeycomb

maint: dockerize go services

---

.gitignore
python/message-service/poetry.lock
python/message-service/pyproject.toml
python/name-service/name_service/__init__.py
python/name-service/poetry.lock
python/name-service/pyproject.toml

- lack of otel python logs examples
- add `venv` to `.gitignore`
- update dependencies in python name and message services
- add otel log to python name service, logging selected year (similar to dotnet service)
- add attributes to python name service
To run, set environment variables and either run `tilt up py` from the root directory, or for a smaller more contained example, `poetry run flask run` from the `python/name-service` directory and `poetry run yearservice/manage.py runserver 0.0.0.0:6001` from the `python/year-service` directory.
If running in Tilt, simply click `curl greeting`. If running individually, in the terminal run `curl localhost:8000/name`

feat: add otel logs to python name service

---

.github/dependabot.yml

- maybe fixes failing "validate-pr-title" workflow
- There is a workflow for "validate-pr-title" that checks for a PR title prefix that matches those in a list; the dependabots should be prepended with "maint" based on the `dependabot.yml` `commit-message: prefix: "maint"`, but it doesn't work. I'm not sure if it's because of a syntax issue or because of multiple ecosystems that don't allow this to work as expected, so thought I'd update the syntax just in case. Some of the `package-ecosystem` lines were not properly aligned and showing an error in my editor, so I updated those and other whitespace to be consistent 🤷 
If this doesn't work (maybe the multiple ecosystem issue), we can try adding "build" to the [list of prefixes](https://github.com/honeycombio/example-greeting-service/blob/ma …

maint: whitespace changes for dependabot

---

go-auto-instrumented/README.md
go-auto-instrumented/greetings-instrumented.yaml

- changes made to go auto-instrumentation 
- update target to new name `OTEL_GO_AUTO_TARGET_EXE` (from `OTEL_TARGET_EXE`)
- update image name from `agent` to `instrumentation`
- add `http://` protocol to endpoint
- consolidate kind commands for loading docker images

maint: update go auto instrumentation

---

java/frontend/Dockerfile
java/message-service/Dockerfile
java/name-service/Dockerfile
java/year-service/Dockerfile

- trying to use openjdk:*-jdk-alpine results in error `no matching manifest for linux/arm64/v8 in the manifest list entries`
- swap out [openjdk](https://hub.docker.com/_/openjdk) for [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin). I could just use a non-alpine image, but it also shows this is a deprecated image (see [here](https://github.com/docker-library/openjdk/issues/505)) so figured I'd swap out now.

maint: use arm-friendly jdk docker images

---

go-auto-instrumented/README.md
go-auto-instrumented/greetings-instrumented.yaml

- update to use the new [published artifact v0.2.0-alpha](https://github.com/open-telemetry/opentelemetry-go-instrumentation/pkgs/container/opentelemetry-go-instrumentation%2Fautoinstrumentation-go/90530735?tag=v0.2.0-alpha)!

maint: update go auto-instr with published image

---

golang/frontend/Dockerfile
golang/go.mod
golang/go.sum
golang/message-service/Dockerfile
golang/name-service/Dockerfile
golang/year-service/Dockerfile
golang/year-service/main.go

- older versions in go services
- update docker images from golang:1.18 -> golang:1.20
- update honeycomb go distro from 0.5.1 -> 0.5.4
- update otel-launcher-go 1.7.0 -> otel-config-go 1.8.0 (name change)
- update usage of launcher/config in year service to new name

maint: Update go services with newer go version and newer distro

---

python/year-service/yearservice/yearservice/settings.py

Year service is blocking connections because it has a list of allowed hosts.
Follow-up to #628 hostname is now year-service.

fix: python year service

---

go-auto-instrumented/greetings-instrumented.yaml

- newer version of go instrumentation available ([release v0.2.2-alpha](https://github.com/open-telemetry/opentelemetry-go-instrumentation/releases/tag/v0.2.2-alpha))
- update image from v0.2.0-alpha to v0.2.2-alpha
- This includes context propagation and client instrumentation
Note there are still some kinks to be worked out (it's alpha) but there is at least a trace for frontend-name-year and frontend-message

maint: update go-instrumentation image

---

java/frontend/src/main/java/io/honeycomb/examples/frontend_java/GreetingController.java

- makeCurrent() creates a closable Scope
- if we don't close it, context can get wonky and mess up span relationships and trace association java otel recommends using try-with-resource block

fix: close new context when using baggage

---

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/add-to-project-v2.yml

- update telemetry-team to pipeline-team for codeowners and dependabot
- add add-to-project workflow to show up on pipeline project board

maint: update telemetry-team to pipeline-team

---

.gitignore
web/package-lock.json
web/package.json
web/src/tracing-http.js

- adding new alpha web sdk to web service
- replace existing tracing setup with new (alpha) honeycomb web distro
`tilt up web node` from the root directory should result in 3 traces, including a 27-span trace connecting the browser to the frontend-message-name-year services

feat: add honeycomb web sdk to browser service

---

docker-compose.node.yml
node/year-service/main.js
node/year-service/package-lock.json
node/year-service/package.json
node/year-service/tracing.js

Updates the node year service to include a logging framework (Bunyan) and generate OTLP logs from log entries.
- Closes https://github.com/honeycombio/example-greeting-service/issues/970
- Update OTel packages to latest
- Add OTLP log exporter and bunyan dependencies
- Configure log processor during NodeSDK setup
- Update year endpoint to also log the selected year
- Update node's docker compose file to set `OTEL_SERVICE_NAME` and `OTEL_EXPORTER_OTLP_HEADERS` env vars

maint: Update node year service to use bunyan logging and send OTLP logs

---

.github/workflows/publish-ghcr.yml

Older ubuntu images used in our workflows are being marked as deprecated. We need to update to newer ones.
- Update workflows images to use `ubuntu-2204:2024.01.1` image

maint: Update ubuntu image in workflows to latest

---

.github/workflows/publish-ghcr.yml

Reverts honeycombio/example-greeting-service#992
I think this was fine actually before this change. I didn't look closely enough. Also we can probably delete because we don't really use it anymore but let's just fix it for now.

fix: Revert "maint: Update ubuntu image in workflows to latest"

---

Tiltfile
golang/year-service/main.go

Updates the golang year service to use plain otel SDK.
- Closes https://github.com/honeycombio/example-greeting-service/issues/968
- Updates golang year service to use base otel SDK instead of honeycomb otel distro
- Add missing env vars in tilt file

maint: update golang/year service to be plain otel

---

ruby/frontend/Dockerfile
ruby/frontend/frontend.ru

- Demonstrate how to ignore endpoints in OTel Ruby instrumentation, particular use case being chatty healthcheck endpoints.
- adds a HEALTHCHECK command to the Dockerfile so that Docker will nag the healthcheck endpoint
- adds OTel instrumentation config to ignore healthcheck endpoint (doesn't generate traces for requests to /up)

feat: add a healthcheck endpoint to frontend-ruby
